#!/bin/bash
rm -rf /etc/services.d/flexget-*
if ls /config/*.yml 1> /dev/null 2>&1; then
for i in /config/*.yml 
do
	file=$(echo $i | sed 's#/config/##g')
	instance=$(echo $file | sed 's#\.yml##g')
	mkdir -p /etc/services.d/flexget-$instance
	sed 's/%%configfile%%/'$file'/g' /var/lib/templates/run > /etc/services.d/flexget-$instance/run 
	chmod +x /etc/services.d/flexget-$instance/run
done
fi
